// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9U8Y84P_7UpzQTie18t3yR25xqgC--1M',
    appId: '1:809743636814:web:0922be6e4c3bf669efa61f',
    messagingSenderId: '809743636814',
    projectId: 'learn-to-code-app-ab4cf',
    authDomain: 'learn-to-code-app-ab4cf.firebaseapp.com',
    storageBucket: 'learn-to-code-app-ab4cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyEpltEltcP4VvIGGih8yV9b6EYFq1Oo',
    appId: '1:809743636814:android:f94791f4b1eeac1fefa61f',
    messagingSenderId: '809743636814',
    projectId: 'learn-to-code-app-ab4cf',
    storageBucket: 'learn-to-code-app-ab4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvfwtkqbc9NdCQvKwU19RD_xeZWpkFhc',
    appId: '1:809743636814:ios:9a864bb33d407407efa61f',
    messagingSenderId: '809743636814',
    projectId: 'learn-to-code-app-ab4cf',
    storageBucket: 'learn-to-code-app-ab4cf.appspot.com',
    iosClientId: '809743636814-sm662j3vip5blhir4b0dibojsss4dsdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLtc',
  );
}
